# Generated by Django 5.2.9 on 2025-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(max_length=128)),
                ('os', models.CharField(max_length=255)),
                ('cpu_model', models.CharField(max_length=255)),
                ('mem_total_mb', models.IntegerField()),
                ('mem_used_mb', models.IntegerField()),
                ('mem_free_mb', models.IntegerField()),
                ('disk_total', models.CharField(max_length=32)),
                ('disk_used', models.CharField(max_length=32)),
                ('disk_avail', models.CharField(max_length=32)),
                ('disk_use_percent', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
