# Generated by Django 5.2.9 on 2025-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetserver',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetserver',
            name='status',
            field=models.CharField(blank=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='assetserver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='disk_avail',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='disk_total',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='disk_use_percent',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='disk_used',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='mem_free_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='mem_total_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='mem_used_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetserver',
            name='os',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='assetserver',
            table='asset_server',
        ),
    ]
